# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sprout' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sprout
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'sproutTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sproutUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
